[versions]
accompanist = "0.32.0"
android-gradle-plugin = "8.2.2"
androidx-activity = "1.8.1"
androidx-compose = "1.5.4"
androidx-compose-ui = "1.5.4"
androidx-compose-compiler = "1.5.5"
androidx-lifecycle = "2.6.2"
dagger = "2.49"
facebook-flipper = "0.240.0"
gtoSupport = "4.0.1"
hamcrest = "2.2"
kotlin = "1.9.20"
kotlinCoroutines = "1.7.3"
kotlinKover = "0.7.5"
ktlint = "0.50.0"
mpdxLib = "3.0.4"
moshi = "1.15.0"
okhttp3 = "4.12.0"
realm = "10.17.0"
retrofit = "2.9.0"

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist"}
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist"}
advrecyclerview = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:1.0.0"
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
androidx-activity-compose = { module = 'androidx.activity:activity-compose', version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-biometric = "androidx.biometric:biometric:1.1.0"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-compose-hilt-navigation = "androidx.hilt:hilt-navigation-compose:1.1.0"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.2.0-alpha10"
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.7.5"
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "androidx-compose-ui" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-databinding-compiler = { module = "androidx.databinding:databinding-compiler", version.ref = "android-gradle-plugin" }
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.6.2"
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
circleindicator = "me.relex:circleindicator:2.1.6"
coil-compose = "io.coil-kt:coil-compose:2.5.0"
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
eventbus = "org.greenrobot:eventbus:3.3.1"
facebook-flipper = { module = "com.facebook.flipper:flipper", version.ref = "facebook-flipper" }
facebook-flipper-plugins-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "facebook-flipper" }
facebook-flipper-plugins-realm = "com.kgurgul.flipper:flipper-realm-android:2.2.0"
facebook-soloader = "com.facebook.soloader:soloader:0.10.5"
firebase-appdistribution-gradlePlugin = "com.google.firebase:firebase-appdistribution-gradle:4.0.1"
firebase-core = "com.google.firebase:firebase-core:21.1.1"
firebase-crashlytics = "com.google.firebase:firebase-crashlytics:18.6.0"
firebase-crashlytics-gradlePlugin = "com.google.firebase:firebase-crashlytics-gradle:2.9.9"
firebase-iid = "com.google.firebase:firebase-iid:21.1.0"
firebase-messaging = "com.google.firebase:firebase-messaging:23.4.0"
firebase-perf = "com.google.firebase:firebase-perf:20.5.1"
firebase-perf-gradlePlugin = "com.google.firebase:perf-plugin:1.4.2"
google-services-gradlePlugin = "com.google.gms:google-services:4.4.0"
gson = "com.google.code.gson:gson:2.10.1"
gtoSupport-api-okhttp3 = {module = "org.ccci.gto.android:gto-support-api-okhttp3", version.ref = "gtoSupport"}
gtoSupport-androidx-fragment = { module = "org.ccci.gto.android:gto-support-androidx-fragment", version.ref = "gtoSupport" }
gtoSupport-androidx-lifecyle = { module = "org.ccci.gto.android:gto-support-androidx-lifecycle", version.ref = "gtoSupport" }
gtoSupport-base = {module = "org.ccci.gto.android:gto-support-base", version.ref = "gtoSupport"}
gtoSupport-compat = {module = "org.ccci.gto.android:gto-support-compat", version.ref = "gtoSupport"}
gtoSupport-core = {module = "org.ccci.gto.android:gto-support-core", version.ref = "gtoSupport"}
gtoSupport-dagger = {module = "org.ccci.gto.android:gto-support-dagger", version.ref = "gtoSupport"}
gtoSupport-facebook-flipper = {module = "org.ccci.gto.android:gto-support-facebook-flipper", version.ref = "gtoSupport"}
gtoSupport-firebase-crashlytics = {module = "org.ccci.gto.android:gto-support-firebase-crashlytics", version.ref = "gtoSupport"}
gtoSupport-jsonapi = {module = "org.ccci.gto.android:gto-support-jsonapi", version.ref = "gtoSupport"}
gtoSupport-jsonapi-retrofit2 = {module = "org.ccci.gto.android:gto-support-jsonapi-retrofit2", version.ref = "gtoSupport"}
gtoSupport-kotlin-coroutines = {module = "org.ccci.gto.android:gto-support-kotlin-coroutines", version.ref = "gtoSupport"}
gtoSupport-leakcanary = {module = "org.ccci.gto.android:gto-support-leakcanary2", version.ref = "gtoSupport"}
gtoSupport-okhttp3 = {module = "org.ccci.gto.android:gto-support-okhttp3", version.ref = "gtoSupport"}
gtoSupport-okta = {module = "org.ccci.gto.android:gto-support-okta", version.ref = "gtoSupport"}
gtoSupport-picasso = {module = "org.ccci.gto.android:gto-support-picasso", version.ref = "gtoSupport"}
gtoSupport-realm = {module = "org.ccci.gto.android:gto-support-realm", version.ref = "gtoSupport"}
gtoSupport-recyclerview = {module = "org.ccci.gto.android:gto-support-recyclerview", version.ref = "gtoSupport"}
gtoSupport-recyclerview-advrecyclerview = {module = "org.ccci.gto.android:gto-support-recyclerview-advrecyclerview", version.ref = "gtoSupport"}
gtoSupport-retrofit2 = {module = "org.ccci.gto.android:gto-support-retrofit2", version.ref = "gtoSupport"}
gtoSupport-testing-okta = { module = "org.ccci.gto.android.testing:gto-support-okta", version.ref = "gtoSupport" }
gtoSupport-testing-picasso = { module = "org.ccci.gto.android.testing:gto-support-picasso", version.ref = "gtoSupport" }
gtoSupport-testing-timber = { module = "org.ccci.gto.android.testing:gto-support-timber", version.ref = "gtoSupport" }
gtoSupport-util = { module = "org.ccci.gto.android:gto-support-util", version.ref = "gtoSupport" }
gtoSupport-viewpager = { module = "org.ccci.gto.android:gto-support-viewpager", version.ref = "gtoSupport" }
guava = "com.google.guava:guava:32.1.3-android"
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest"}
hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
javapoet = "com.squareup:javapoet:1.13.0"
json = "org.json:json:20231013"
junit = "junit:junit:4.13.2"
junit-params = "pl.pragmatists:JUnitParams:1.1.1"
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinCoroutines" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-kover-gradlePlugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kotlinKover" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref="kotlin"}
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.12"
materialComponents = "com.google.android.material:material:1.11.0"
mpdx-lib-lib = { module = "org.cru.mpdx.android:library", version.ref = "mpdxLib"}
mpdx-lib-core = { module ="org.cru.mpdx.android:core", version.ref = "mpdxLib"}
mpdx-lib-okta = { module ="org.cru.mpdx.android:okta", version.ref = "mpdxLib"}
mpdx-lib-oauth = { module ="org.cru.mpdx.android:oauth", version.ref = "mpdxLib"}
mockito = "org.mockito:mockito-inline:5.2.0"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.2.1"
mockk = "io.mockk:mockk:1.13.8"
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
mpAndroidChart = "com.github.PhilJay:MPAndroidChart:3.1.0"
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-interceptors-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }
onesky-gradlePlugin = "co.brainly:plugin:1.6.0"
openid-appauth = "net.openid:appauth:0.11.1"
picasso = "com.squareup.picasso:picasso:2.8"
picasso-transformations = "jp.wasabeef:picasso-transformations:2.4.0"
play-tagmanager = "com.google.android.gms:play-services-tagmanager:18.0.4"
realm = { module = "io.realm:realm-android-library", version.ref = "realm" }
realm-fieldnameshelper = "dk.ilios:realmfieldnameshelper:2.0.0"
realm-gradlePlugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realm" }
recyclertablayout-androidx = "com.ochim:recyclertablayout-androidx:2.0.0"
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
robolectric = "org.robolectric:robolectric:4.11.1"
rxjava = "io.reactivex.rxjava2:rxjava:2.2.21"
speed-dial = "com.leinardi.android:speed-dial:3.3.0"
splitties-fragmentargs = "com.louiscad.splitties:splitties-fragmentargs:3.0.0"
threetenbp-android = "com.jakewharton.threetenabp:threetenabp:1.4.6"
threetenbp = "org.threeten:threetenbp:1.6.8"
timber = "com.jakewharton.timber:timber:5.0.1"
weakDelegate = "com.github.Karumi:WeakDelegate:1.0.1"

# HACK: dependencies used to trigger renovate upgrades
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }

[bundles]
androidx-compose = ["androidx-compose-runtime-livedata", "androidx-compose-ui", "androidx-compose-ui-tooling-preview"]

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
grgit = { id = "org.ajoberstar.grgit", version = "5.2.1" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.0.2" }
